# Lalumo App Zentrale Konfiguration
# Enth채lt umgebungsspezifische Einstellungen f체r Entwicklung und Produktion

# Entwicklungsumgebung (localhost)
development:
  # Backend API URL (PHP)
  API_BASE_URL: http://localhost:8080
  # Frontend App URL
  APP_BASE_URL: http://localhost:9091
  # Basis-Pfad f체r Assets
  APP_BASE_PATH: /

# Produktionsumgebung (lalumo.eu)
production:
  # Backend API URL (PHP)
  API_BASE_URL: https://lalumo.eu/app
  # Frontend App URL
  APP_BASE_URL: https://lalumo.eu/app
  # Basis-Pfad f체r Assets
  APP_BASE_PATH: /app/
